version: "3"

services:
  mongodb:
    image: mongo:4.0.4
    container_name: "leroy-database"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/var/lib/mongodb/data
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "leroy-queue"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_ERLANG_COOKIE: erlangcookie
      RABBITMQ_DEFAULT_USER: rabbitmquser
      RABBITMQ_DEFAULT_PASS: rabbitmqpass
    ports:
      - 5672:5672
      - 15672:15672
      - 25676:25676
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge

volumes:
  mongodb:
    driver: local
  rabbitmq:
    driver: local
